### ISSUE TITLE
Problem with mixers on FreeBSD 10

### ISSUE THREAD

**Issue by imhoil** [ircmaxell/RandomLib#40]
I have FreeBSD 10 + nginx + php56-fpm
install owncloud from ports, reinstall from pkg
In both cases, the installation went normally
But the logs Nginx
2015/09/23 09:06:17 [error] 64306#0: *62634 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Could not find mixer' in /usr/local/www/nginx-dist/oc/3rdparty/ircmaxell/random-lib/lib/RandomLib/Factory.php:187
Stack trace:
#0 /usr/local/www/nginx-dist/oc/3rdparty/ircmaxell/random-lib/lib/RandomLib/Factory.php(68): RandomLib\Factory->findMixer(Object(SecurityLib\Strength))
#1 /usr/local/www/nginx-dist/oc/3rdparty/ircmaxell/random-lib/lib/RandomLib/Factory.php(95): RandomLib\Factory->getGenerator(Object(SecurityLib\Strength))
#2 /usr/local/www/nginx-dist/oc/lib/private/security/securerandom.php(59): RandomLib\Factory->getLowStrengthGenerator()
#3 /usr/local/www/nginx-dist/oc/lib/private/appframework/http/request.php(439): OC\Security\SecureRandom->getLowStrengthGenerator()
#4 /usr/local/www/nginx-dist/oc/lib/private/log/owncloud.php(77): OC\AppFramework\Http\Request->getId()
#5 [internal function]: OC_Log_Owncloud::write('PHP', 'RuntimeExceptio...', 3)
#6 /usr/local/www/nginx-dist/oc/lib/private/log.php(241): call_user_...

**Comment by ircmaxell** [comment]
Why are you using low strength? Why not use medium?

**Comment by imhoil** [comment]
Im try using owncloud, its default.

**Comment by ircmaxell** [comment]
Can you try using the library directly? Without owncloud and see if you can reproduce it?

**Comment by imhoil** [comment]
I can, but it's difficult to do that, I'm not a programmer
The same package owncloud, from official site, on Ubuntu 14.04 working normally. It seems to me that a some package was installed on freebsd with the wrong parameters.

**Comment by imhoil** [comment]
Problem solved. Clean install FreeBSD 10.2 :)
